apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  selector:
    app: spring-app
  ports:
  - protocol: TCP
    port: 80  # 외부 포트
    targetPort: 8080  # Spring 컨테이너 포트
  type: LoadBalancer  # 외부 트래픽을 허용하기 위한 타입
